PruebaBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        IDX_2265B05DF5F88DB9:
            columns:
                - persona_id
    uniqueConstraints:
        usuario_nombre_key:
            columns:
                - nombre
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        correo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        clave:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        persona:
            targetEntity: Persona
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                persona_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
